ALTER TABLE company ALTER COLUMN company_id TYPE BIGINT;
ALTER TABLE company_characteristic ALTER COLUMN com_char_id TYPE BIGINT;
ALTER TABLE offer ALTER COLUMN offer_id TYPE BIGINT;
ALTER TABLE offer_characteristic ALTER COLUMN offer_char_id TYPE BIGINT;
ALTER TABLE photo ALTER COLUMN photo_id TYPE BIGINT;
ALTER TABLE price ALTER COLUMN price_id TYPE BIGINT;
ALTER TABLE review ALTER COLUMN review_id TYPE BIGINT;
ALTER TABLE work_time ALTER COLUMN work_time_id TYPE BIGINT;
