package com.server.catalog.models;
// Generated Nov 18, 2023, 1:55:17 PM by Hibernate Tools 6.2.13.Final


import java.sql.Date;
import java.util.HashSet;
import java.util.Set;

import org.geolatte.geom.Geometry;
import org.hibernate.spatial.dialect.postgis.PGGeographyJdbcType;
import org.locationtech.jts.geom.Point;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;



/**
 * city generated by hbm2java
 * @param <PGobject>
 * @param <PGobject>
 */
@SuppressWarnings("unused")
@Entity
@Table(name = "city", schema = "constants")
public class City implements java.io.Serializable {


	/**
	 * 
	 */
	private static final long serialVersionUID = 2370980474414506156L;
	
	@Id
	private long cityId;
	private Double latitude;
	private Double longitude;
	private Long population;
	private Date populationDate;
	
	@Column(columnDefinition = "Geography(Point,4326)")
	private Point location;
	
    @OneToMany(mappedBy = "city", cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private Set<CityTag> cityTags = new HashSet<CityTag>(0);
    @OneToMany(mappedBy = "city",cascade = CascadeType.ALL, fetch = FetchType.LAZY)
	private Set<CityName> cityNames = new HashSet<CityName>(0);
    

	public City() {
	}

	public City(long cityId) {
		this.cityId = cityId;
	}

	public City(long cityId, Double latitude, Double longitude, Long population, Date populationDate,
			Point location, Set<CityTag> cityTags, Set<CityName> cityNames) {
		this.cityId = cityId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.population = population;
		this.populationDate = populationDate;
		this.location = location;
		this.cityTags = cityTags;
		this.cityNames = cityNames;
	}

	public long getCityId() {
		return this.cityId;
	}

	public void setCityId(long cityId) {
		this.cityId = cityId;
	}

	public Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(Double latitude) {
		this.latitude = latitude;
	}

	public Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(Double longitude) {
		this.longitude = longitude;
	}

	public Long getPopulation() {
		return this.population;
	}

	public void setPopulation(Long population) {
		this.population = population;
	}

	public Date getPopulationDate() {
		return this.populationDate;
	}

	public void setPopulationDate(Date populationDate) {
		this.populationDate = populationDate;
	}

	public Point getLocation() {
		return this.location;
	}

	public void setLocation(Point location) {
		this.location = location;
	}

	public Set<CityTag> getCityTags() {
		return this.cityTags;
	}

	public void setCityTagses(Set<CityTag> cityTags) {
		this.cityTags = cityTags;
	}

	public Set<CityName> getCityNames() {
		return this.cityNames;
	}

	public void setCityNameses(Set<CityName> cityNames) {
		this.cityNames = cityNames;
	}

}
