package com.server.catalog.models;

import jakarta.persistence.EmbeddedId;
import jakarta.persistence.Entity;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.MapsId;
import jakarta.persistence.Table;

// Generated Nov 18, 2023, 1:55:17 PM by Hibernate Tools 6.2.13.Final

/**
 * CityTags generated by hbm2java
 */
@Entity
@Table(name = "city_tag", schema = "constants")
public class CityTag implements java.io.Serializable {



	/**
	 * 
	 */
	private static final long serialVersionUID = 4060561693110326951L;

	@EmbeddedId
	private CityTagId id;
	
	@ManyToOne
	@MapsId("cityTagId")
    @JoinColumn(name = "city_tag_id") // Указывает на столбец внешнего ключа в таблице CityTags
	private City city;

	public CityTag() {
	}

	public CityTag(CityTagId id) {
		this.id = id;
	}

	public CityTag(CityTagId id, City city) {
		this.id = id;
		this.city = city;
	}

	public CityTagId getId() {
		return this.id;
	}

	public void setId(CityTagId id) {
		this.id = id;
	}

	public City getCity() {
		return this.city;
	}

	public void setCity(City city) {
		this.city = city;
	}

}
