package com.server.catalog.models;

import jakarta.persistence.Embeddable;
import jakarta.persistence.Id;

// Generated Nov 18, 2023, 1:55:17 PM by Hibernate Tools 6.2.13.Final

/**
 * CityNamesId generated by hbm2java
 */
@Embeddable
public class CityNameId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1110716775906010503L;

	private long cityNameId;
	private String language;
	private String name;

	public CityNameId() {
	}

	public CityNameId(Long cityNameId, String language, String name) {
		this.cityNameId = cityNameId;
		this.language = language;
		this.name = name;
	}

	public Long getCityNameId() {
		return this.cityNameId;
	}

	public void setCityNamesId(Long cityNamesId) {
		this.cityNameId = cityNamesId;
	}

	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CityNameId))
			return false;
		CityNameId castOther = (CityNameId) other;

		return ((this.getCityNameId() == castOther.getCityNameId()) || (this.getCityNameId() != null
				&& castOther.getCityNameId() != null && this.getCityNameId().equals(castOther.getCityNameId())))
				&& ((this.getLanguage() == castOther.getLanguage()) || (this.getLanguage() != null
						&& castOther.getLanguage() != null && this.getLanguage().equals(castOther.getLanguage())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null && castOther.getName() != null
						&& this.getName().equals(castOther.getName())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getCityNameId() == null ? 0 : this.getCityNameId().hashCode());
		result = 37 * result + (getLanguage() == null ? 0 : this.getLanguage().hashCode());
		result = 37 * result + (getName() == null ? 0 : this.getName().hashCode());
		return result;
	}

}
