package com.server.catalog.models;
// Generated Mar 6, 2024, 11:20:35 PM by Hibernate Tools 6.2.13.Final

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;

/**
 * CompanyCharacteristics generated by hbm2java
 */
@Entity
public class CompanyCharacteristic implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9212591778412565260L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "company_characteristics_seq_generator")
	@SequenceGenerator(name="company_characteristics_seq_generator", sequenceName = "company_characteristics_seq", allocationSize=1)
	private Long comCharId;
	
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
	private Company company;
	private String charCategory;
	private String charKey;
	//private String charValue;
	private String icon;

	public CompanyCharacteristic() {
	}

	public CompanyCharacteristic(Long comCharId) {
		this.comCharId = comCharId;
	}

	public CompanyCharacteristic(Long comCharId, Company company, String charCategory, String charKey, String icon) {
		this.comCharId = comCharId;
		this.company = company;
		this.charCategory = charCategory;
		this.charKey = charKey;
		//this.charValue = charValue;
		this.icon = icon;
	}

	public Long getComCharId() {
		return this.comCharId;
	}

	public void setComCharId(Long comCharId) {
		this.comCharId = comCharId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getCharCategory() {
		return this.charCategory;
	}

	public void setCharCategory(String charCategory) {
		this.charCategory = charCategory;
	}

	public String getCharKey() {
		return this.charKey;
	}

	public void setCharKey(String charKey) {
		this.charKey = charKey;
	}

//	public String getCharValue() {
//		return this.charValue;
//	}
//
//	public void setCharValue(String charValue) {
//		this.charValue = charValue;
//	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

}
