package com.server.catalog.models;
// Generated Mar 6, 2024, 11:20:35 PM by Hibernate Tools 6.2.13.Final

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToMany;
import jakarta.persistence.SequenceGenerator;

/**
 * Offers generated by hbm2java
 */
@Entity
public class Offer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3911136357732535097L;
	
	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "offer_seq_generator")
    @SequenceGenerator(name="offer_seq_generator", sequenceName = "offer_seq", allocationSize = 1)
	private Long offerId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
	private Company company;
	private String categoryOffer;
	private String type;
	private String title;
	private String description;
	@OneToMany(mappedBy = "offer")
	private Set<Photo> photos = new HashSet<Photo>(0);
	@OneToMany(mappedBy = "offer")
	private Set<OfferCharacteristic> offerCharacteristics = new HashSet<OfferCharacteristic>(0);

	public Offer() {
	}

	public Offer(Long offerId) {
		this.offerId = offerId;
	}

	public Offer(Long offerId, Company company, String categoryOffer, String type, String title,
			String description, String photo, Set<Photo> photos, Set<OfferCharacteristic> offerCharacteristics) {
		this.offerId = offerId;
		this.company = company;
		this.categoryOffer = categoryOffer;
		this.type = type;
		this.title = title;
		this.description = description;
		this.photos = photos;
		this.offerCharacteristics = offerCharacteristics;
	}

	public Long getOfferId() {
		return this.offerId;
	}

	public void setOfferId(Long offerId) {
		this.offerId = offerId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getCategoryOffer() {
		return this.categoryOffer;
	}

	public void setCategoryOffer(String categoryOffer) {
		this.categoryOffer = categoryOffer;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}


	public Set<Photo> getPhotos() {
		return this.photos;
	}

	public void setPhotos(Set<Photo> photos) {
		this.photos = photos;
	}

	public Set<OfferCharacteristic> getOfferCharacteristics() {
		return this.offerCharacteristics;
	}

	public void setOfferCharacteristics(Set<OfferCharacteristic> offerCharacteristics) {
		this.offerCharacteristics = offerCharacteristics;
	}

}
