package com.server.catalog.models;
// Generated Mar 6, 2024, 11:20:35 PM by Hibernate Tools 6.2.13.Final

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;

/**
 * Photos generated by hbm2java
 */
@Entity
public class Photo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2300004205875657682L;
	
	@Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "photo_seq_generator")
    @SequenceGenerator(name="photo_seq_generator", sequenceName = "photo_seq", allocationSize = 1)
	private Long photoId;
	@ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "company_id")
	private Company company;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "offer_id")
	private Offer offer;
	private String photoName;
	private String photoLink;

	public Photo() {
	}

	public Photo(Long photoId) {
		this.photoId = photoId;
	}

	public Photo(Long photoId, Company company, Offer offer, String photoName, String photoLink) {
		this.photoId = photoId;
		this.company = company;
		this.offer = offer;
		this.photoName = photoName;
		this.photoLink = photoLink;
	}

	public Long getPhotoId() {
		return this.photoId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public Offer getOffer() {
		return this.offer;
	}

	public void setOffer(Offer offer) {
		this.offer = offer;
	}

	public String getPhotoName() {
		return this.photoName;
	}

	public void setPhotoName(String photoName) {
		this.photoName = photoName;
	}

	public String getPhotoLink() {
		return this.photoLink;
	}

	public void setPhotoLink(String photoLink) {
		this.photoLink = photoLink;
	}

}
