package com.server.catalog.models;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.SequenceGenerator;
import jakarta.persistence.Table;

// Generated Mar 26, 2024, 8:54:54 PM by Hibernate Tools 6.2.13.Final

/**
 * Reference generated by hbm2java
 */
@Entity
@Table(name = "reference", schema = "constants")
public class Reference implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2937420121870315832L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "reference_seq_generator")
    @SequenceGenerator(name="reference_seq_generator", sequenceName = "reference_seq", allocationSize = 1)
	private long referenceId;
	private String scope;
	private String key;
	private String value;
	private String icon;
	private Integer sortOrder;

	public Reference() {
	}

	public Reference(long referenceId, String scope, String key, String value) {
		this.referenceId = referenceId;
		this.scope = scope;
		this.key = key;
		this.value = value;
	}

	public Reference(long referenceId, String scope, String key, String value, String icon, Integer sortOrder) {
		this.referenceId = referenceId;
		this.scope = scope;
		this.key = key;
		this.value = value;
		this.icon = icon;
		this.sortOrder = sortOrder;
	}

	public long getReferenceId() {
		return this.referenceId;
	}

	public void setReferenceId(long referenceId) {
		this.referenceId = referenceId;
	}

	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getIcon() {
		return this.icon;
	}

	public void setIcon(String icon) {
		this.icon = icon;
	}

	public Integer getSortOrder() {
		return this.sortOrder;
	}

	public void setSortOrder(Integer sortOrder) {
		this.sortOrder = sortOrder;
	}

}
