package com.server.catalog.models;
// Generated Mar 6, 2024, 11:20:35 PM by Hibernate Tools 6.2.13.Final

import java.util.Date;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;

/**
 * Reviews generated by hbm2java
 */
@Entity
public class Review implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7135053085208903217L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "review_seq_generator")
    @SequenceGenerator(name="review_seq_generator", sequenceName = "review_seq", allocationSize = 1)
	private Long reviewId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	private Company company;
	private String photo;
	private String title;
	private Date date;
	private double rating;
	private String reviewContent;
	private Integer reviewLike;
	private Integer reviewUnlike;

	public Review() {
	}

	public Review(Long reviewId) {
		this.reviewId = reviewId;
	}

	public Review(Long reviewId, Company company, String photo, String title, Date date, Integer rating,
			String reviewContent, Integer reviewLike, Integer reviewUnlike) {
		this.reviewId = reviewId;
		this.company = company;
		this.photo = photo;
		this.title = title;
		this.date = date;
		this.rating = rating;
		this.reviewContent = reviewContent;
		this.reviewLike = reviewLike;
		this.reviewUnlike = reviewUnlike;
	}

	public Long getReviewId() {
		return this.reviewId;
	}


	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	public double getRating() {
		return this.rating;
	}

	public void setRating(Double rating) {
		this.rating = rating;
	}

	public String getReviewContent() {
		return this.reviewContent;
	}

	public void setReviewContent(String reviewContent) {
		this.reviewContent = reviewContent;
	}

	public Integer getReviewLike() {
		return this.reviewLike;
	}

	public void setReviewLike(Integer reviewLike) {
		this.reviewLike = reviewLike;
	}

	public Integer getReviewUnlike() {
		return this.reviewUnlike;
	}

	public void setReviewUnlike(Integer reviewUnlike) {
		this.reviewUnlike = reviewUnlike;
	}

}
