package com.server.catalog.models;
// Generated Mar 6, 2024, 11:20:35 PM by Hibernate Tools 6.2.13.Final

import java.sql.Time;

import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.SequenceGenerator;

/**
 * WorkTimes generated by hbm2java
 */
@Entity
public class WorkTime implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4301913434454160891L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "work_time_seq_generator")
    @SequenceGenerator(name="work_time_seq_generator", sequenceName = "work_time_seq", allocationSize = 1)
	private Long workTimeId;
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	private Company company;
	private String dayOfWeek;
	private Time startTime;
	private Time endTime;
	private String note;

	public WorkTime() {
	}

	public WorkTime(Long workTimeId) {
		this.workTimeId = workTimeId;
	}

	public WorkTime(Long workTimeId, Company company, String dayOfWeek, Time startTime, Time endTime,
			String note) {
		this.workTimeId = workTimeId;
		this.company = company;
		this.dayOfWeek = dayOfWeek;
		this.startTime = startTime;
		this.endTime = endTime;
		this.note = note;
	}

	public Long getWorkTimeId() {
		return this.workTimeId;
	}

	public void setWorkTimeId(Long workTimeId) {
		this.workTimeId = workTimeId;
	}

	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	public String getDayOfWeek() {
		return this.dayOfWeek;
	}

	public void setDayOfWeek(String dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}

	public Time getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Time startTime) {
		this.startTime = startTime;
	}

	public Time getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Time endTime) {
		this.endTime = endTime;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
